:contact-mail: jobroom-api@seco.admin.ch
= Job-Room Jobs API Documentation v1.0
Seco eGovernment Services <{contact-mail}>
:doctype: book
:source-highlighter: highlightjs
:toc: left
:icons: font

:sectnums:
:sectnumlevels: 2

= Access credentials

- For testing use (link:{api-url}/jobAdvertisements/v1[{api-url}/jobAdvertisements/v1]). Test users apiuser01 to apiuser99
are available (password same as user name). Do NOT use any confidetnial data in the test environment but DO use real postal codes.
- The URL for the productive API is https://api.job-room.ch/jobAdvertisements/v1
- If you have integrated and tested the Jobs API and wish to request productive access credentials:
* Send a message with subject "Job-Room API access" to jobroom-api@seco.admin.ch
* Specify the company name, address and email, at least one technical contact person with email address and phone number, and user name. Please also specify the expected volume of job registrations.
* The technical contact will receive an email with further instructions.

= Important updates
Please do not use html tags in job advertisements. Use Markdown formating instead. The reason is that job center agents
can see the ad only in text mode and the html tags make them difficult to read.

For markdown, refer to
* http://en.wikipedia.org/wiki/Markdown
* http://zaclem01.github.io/angular-markdown-previewer/
* htpp://html2markdown.bayn.es

= General

include::api-general.adoc[]

= Jobs advertisement API

include::api-create.adoc[]

include::api-getAll.adoc[]

include::api-get.adoc[]

include::api-update.adoc[]

include::api-cancel.adoc[]

= Appendix

include::api-appendix.adoc[]
