:contact-mail: jobroom-api@seco.admin.ch
= Job-Room Jobs API Documentation v1.0
Seco eGovernment Services <{contact-mail}>
:doctype: book
:source-highlighter: highlightjs
:toc: left
:icons: font

:sectnums:
:sectnumlevels: 2

= Preparation for Go-Live of Job-Room V2.1 and Jobs API V1.0

- In preparation of Go-Live, on June 27, the Job-Room will be taken offline and the legacy Jobs API will be disabled.
- On July 1, the Job-Room 2.1 will go live together with the Jobs API V1.0.
- The URL for the productive API is https://api.job-room.ch/jobAdvertisements/v1
- If you have integrated and tested the Jobs API and wish to request productive access credentials:
* Send a message with subject "Job-Room API access" to jobroom-api@seco.admin.ch
* Specify the company name, address and email, at least one technical contact person with email address and phone number, and user name. Please also specify the expected volume of job registrations.
* The technical contact will receive an email with further instructions.

= General

include::api-general.adoc[]

= Jobs advertisement API

include::api-create.adoc[]

include::api-getAll.adoc[]

include::api-get.adoc[]

include::api-update.adoc[]

include::api-cancel.adoc[]

= Appendix

include::api-appendix.adoc[]
