== Create a new job advertisement

=== Fields

==== JobAdvertisement
[cols="30,10,30,20,50"]
|===
| Path | Type | Description | Constraints | Notes

| externalUrl | String | Link to the original website of the job ad | Optional | For jobs that fall under the reporting obligation, the ad must not be published elsewhere.
| externalReference | String | Your internal reference to this job ad | Optional |
| reportToAvam | Boolean | Should the ad be transmitted to the PES (RAV)? | Required (`true` or `false`) | Use this option if you want a PES agent to know about your vacancy
| contact | <<Contact>> | Contact person about the job ad | Required | Administrative contact, not for publication
| jobDescriptions | Array<<<JobDescription>>> | Language specific title and description | Required 1..4 | The text of the job advertisement; may be multilingual
| company | <<Company>> | The company that handles the recruitment | Required | May be a private employment agency acting as surrogate
| employer | <<Employer>> | The actual employer that offers the job | Required, if _company.surrogate_ is `true` | For administrative purposes, not for publication
| employment | <<Employment>> | Certain employment conditions | Required |
| location | <<Location>> | The work location | Required |
| occupation | <<Occupation>> | Occupation, education and work experience | Required |
| languageSkills | Array<<<LanguageSkill>>> | It is possible to define up to 5 language skills required by the job. | 0..5 objects |
| publicContact | <<PublicContact>> | Contact person for the job seekers questions | Optional | Will be published in Job-Room
| applyChannel | <<ApplyChannel>> | Different application channels | Optional | Provide at least one application channel
| publication | <<Publication>> | The publication platforms | Required | You can control how your ad is published
|===

==== Contact
Provide an administrative contact (e. g. an HR employee); this contact is used for email notifications concerning the reporting obligation
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| languageIsoCode | String | The language of correspondence | Required (ISO 639), must be one of de, fr, it,en
| salutation | String |  | Required (`MR` or `MS`)
| firstName | String |  | Required
| lastName | String |  | Required
| phone | String |  | Required (Format: +41123456789)
| email | String | Multiple comma separated addresses allowed | Required
|===

==== JobDescription
The text of the job advertisement; may be multilingual
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| languageIsoCode | String | The language of the title and description | Required (ISO 639) but only de, fr, it or en
| title | String | Job title or occupation | Required
| description | String | Job description can contain basic HTML formatting as well as markdown convention | Required (Max 10'000 characters)
|===

==== Company
The company that handles the recruitment. This information is published.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| name | String | The name of the company | Required
| street | String | | Optional
| houseNumber | String | | Optional
| postalCode | String | | Required. Must be a valid swiss postal code if the company is located in Switzerland
| city | String | | Required
| countryIsoCode | String | | Required (ISO 3166-1 alpha-2)
| website | String | | Optional (Format: http://www.example.org)
| phone | String | | Optional (Format: +41123456789)
| email | String | | Optional
| surrogate | String | Does the company act as a surrogate for the actual employer? | Required (`true` or `false`)
|===

==== Employer
Must be provided if the company handling the recruitment is not the actual employer; will not be published.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| name | String | The name of the original company | Required
| city | String | | Required
| postalCode | String | | Required. Must be a valid swiss postal code if the company is located in Switzerland
| countryIsoCode | String | | Required (ISO 3166-1 alpha-2)
|===

==== Employment
Employment metadata
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| startDate | String | When does the job start | Optional (Format: 2018-01-20)
| endDate | String | When does the contract end | Optional (Format: 2018-01-20)
| shortEmployment | Boolean | Is the employment duration 14 days or less | Required (`true` or `false`)
| immediately | Boolean | Does the job start immediately | Required (`true` or `false`) `true` only if no startDate is set
| permanent | Boolean | Is the contract permanent | Required (`true` or `false`) `true` only if no endDate is set
| workloadPercentageMin | String | | Required (10..100 less or equal workloadPercentageMax)
| workloadPercentageMax | String | | Required (10..100 greater or equal workloadPercentageMin)
| workForms | Array<String> | Special work requirements | Optional (`SUNDAY_AND_HOLIDAYS`, `SHIFT_WORK`, `NIGHT_WORK`, `HOME_WORK`)
|===

==== Location
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| postalCode | String | | Required. Must be a valid swiss postal code if the company is located in Switzerland
| city | String | The (main) place of work | Required
| countryIsoCode | String | | Required (ISO 3166-1 alpha-2)
| remarks | String | More information about job location can be added as free text.
|===

==== Occupation
The ad must be coded to an occupation according ot the AVAM occupation list; this determines the reporting obligation.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| avamOccupationCode | String | <<AVAM occupation code>>  | Required
| workExperience | String | | Optional (`LESS_THAN_1_YEAR`, `MORE_THAN_1_YEAR` or `MORE_THAN_3_YEARS`)
| educationCode | String | <<AVAM education code>> | Optional
|===

==== LanguageSkill
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| languageIsoCode | String | | Required (ISO 639)
| spokenLevel | String | | Required (`NONE`, `BASIC`, `INTERMEDIATE` or `PROFICIENT`) (see https://en.wikipedia.org/wiki/Common_European_Framework_of_Reference_for_Languages#Common_reference_levels[Common reference levels])
| writtenLevel | String | | Required (`NONE`, `BASIC`, `INTERMEDIATE` or `PROFICIENT`) (see https://en.wikipedia.org/wiki/Common_European_Framework_of_Reference_for_Languages#Common_reference_levels[Common reference levels])
|===

==== ApplyChannel
Provide at least one channel for applications.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| formUrl | String | An online form where an applicant can apply | Optional (Format: http://www.example.org)
| emailAddress | String | An email address where an applicant can send their application | Optional
| phoneNumber | String | A phone number where an applicant can call | Optional (Format: +41123456789)
| mailAddress | String | A post address where an applicant can send their application | Optional
| additionalInfo | String | More application information can be added as free text. | Optional (Max 255 characters)
|===

==== PublicContact
Provide a public contact if you want to give applicants the opportunity to ask questions about the job.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| salutation | String |  | Required (`MR` or `MS`)
| firstName | String |  | Required
| lastName | String |  | Required
| phone | String |  | Required (Format: +41123456789)
| email | String |  | Required
|===

==== Publication
If the ad falls under the reporting obligation, the ad will be restricted for five business days.
After that period, the ad will be published
in the Job-Room public area if the publicDisplay flag is set, otherwise not.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| startDate | String | When does the advertisement publication start | Required (Format: 2018-01-20)
| endDate | String | When does the advertisement publication end (max 60 days) | Optional (Format: 2018-01-20)
| euresDisplay | Boolean | Should the job ad be displayed in Eures | Required (`true` or `false`)
| publicDisplay | Boolean | Should the job ad be displayed in Job-Room public area | Required (`true` or `false`)
|===

=== Request
`POST /api/jobadvertisements`

[source,json]
----
{
    "externalUrl": "string",
    "externalReference": "string",
    "reportToAvam": true,
    "contact": {
        "languageIsoCode": "string",
        "salutation": "string",
        "firstName": "string",
        "lastName": "string",
        "phone": "string",
        "email": "string"
    },
    "jobDescriptions": [
        {
            "languageIsoCode": "string",
            "title": "string",
            "description": "string"
        }
    ],
    "company": {
        "name": "string",
        "street": "string",
        "houseNumber": "string",
        "postOfficeBoxNumber": "string",
        "postOfficeBoxPostalCode": "string",
        "postOfficeBoxCity": "string",
        "postalCode": "string",
        "city": "string",
        "countryIsoCode": "string",
        "website": "string",
        "phone": "string",
        "email": "string",
        "surrogate": true
    },
    "employer": {
        "name": "string",
        "postalCode": "string",
        "city": "string",
        "countryIsoCode": "string"
    },
    "employment": {
        "startDate": "string",
        "endDate": "string",
        "shortEmployment": true,
        "immediately": true,
        "permanent": true,
        "workloadPercentageMax": 0,
        "workloadPercentageMin": 0,
        "workForms": [
            "string"
        ]
    },
    "location": {
        "remarks": "string",
        "postalCode": "string",
        "city": "string",
        "countryIsoCode": "string"
    },
    "occupation": {
        "avamOccupationCode": "string",
        "workExperience": "string",
        "educationCode": "string"
    },
    "languageSkills": [
        {
            "languageIsoCode": "string",
            "spokenLevel": "string",
            "writtenLevel": "string"
        }
    ],
    "applyChannel": {
        "mailAddress": "string",
        "emailAddress": "string",
        "phoneNumber": "string",
        "formUrl": "string",
        "additionalInfo": "string"
    },
    "publicContact": {
        "salutation": "string",
        "firstName": "string",
        "lastName": "string",
        "phone": "string",
        "email": "string"
    },
    "publication": {
        "startDate": "string",
        "endDate": "string",
        "euresDisplay": true,
        "publicDisplay": true
    }
}
----

=== Response
The response provides the _id_ needed to later retrieve the object via Get.
The flag _reportingObligation_ indicates whether the ad falls under the reporting obligation,
based on the occupation code provided.

[source,json]
----
{
    "id": "string",
    "status": "string",
    "sourceSystem": "string",
    "stellennummerEgov": "string",
    "stellennummerAvam": "string",
    "externalReference": "string",
    "fingerprint": "string",
    "jobCenterCode": "string",
    "reportToAvam": true,
    "reportingObligation": true,
    "reportingObligationEndDate": "string",
    "approvalDate": "string",
    "rejectionCode": "string",
    "rejectionDate": "string",
    "rejectionReason": "string",
    "cancellationCode": "string",
    "cancellationDate": "string",
    "jobContent": {
        "externalUrl": "string",
        "jobDescriptions": [
            {
                "languageIsoCode": "string",
                "title": "string",
                "description": "string"
            }
        ],
        "company": {
            "name": "string",
            "street": "string",
            "houseNumber": "string",
            "postOfficeBoxNumber": "string",
            "postOfficeBoxPostalCode": "string",
            "postOfficeBoxCity": "string",
            "postalCode": "string",
            "city": "string",
            "countryIsoCode": "string",
            "website": "string",
            "phone": "string",
            "email": "string",
            "surrogate": true
        },
        "employment": {
            "startDate": "string",
            "endDate": "string",
            "shortEmployment": true,
            "immediately": true,
            "permanent": true,
            "workloadPercentageMax": 0,
            "workloadPercentageMin": 0,
            "workForms": [
                "string"
            ]
        },
        "location": {
            "remarks": "string",
            "postalCode": "string",
            "city": "string",
            "communalCode": "string",
            "regionCode": "string",
            "cantonCode": "string",
            "countryIsoCode": "string",
            "coordinates": {
                "latitude": 0,
                "longitude": 0
            }
        },
        "occupations": [
            {
                "avamOccupationCode": "string",
                "workExperience": "string",
                "educationCode": "string"
            }
        ],
        "languageSkills": [
            {
                "languageIsoCode": "string",
                "spokenLevel": "string",
                "writtenLevel": "string"
            }
        ],
        "applyChannel": {
            "mailAddress": "string",
            "emailAddress": "string",
            "phoneNumber": "string",
            "formUrl": "string",
            "additionalInfo": "string"
        },
        "publicContact": {
            "salutation": "string",
            "firstName": "string",
            "lastName": "string",
            "phone": "string",
            "email": "string"
        }
    },
    "publication": {
        "startDate": "string",
        "endDate": "string",
        "euresDisplay": true,
        "euresAnonymous": true,
        "publicDisplay": true,
        "publicAnonymous": true,
        "restrictedDisplay": true,
        "restrictedAnonymous": true
    }
}
----

=== Response status
[cols="10,20,70"]
|===
| Code | Status | Description

| 201 | Created | The job ad has been successfully created
| 400 | Bad Request | The request was malformed or invalid
| 401 | Unauthorized | User is not logged in
| 403 | Forbidden | User has not the required permission to perform this action
|===

