== Get all job advertisements belonging to the owner

=== Request
`GET {api-url}?page=0&size25`

[cols="10,10,10,70"]
|===
| Parameter | Constraints | Default | Description

| page | Optional | 0 | The page that should be returned
| size | Optional | 25 | The maximum number of elements on the page
|===

=== Response
[source,json]
----
{
    "content": [
        {
            "id": "string",
            "status": "string",
            "sourceSystem": "string",
            "stellennummerEgov": "string",
            "stellennummerAvam": "string",
            "externalReference": "string",
            "fingerprint": "string",
            "jobCenterCode": "string",
            "reportToAvam": true,
            "reportingObligation": true,
            "reportingObligationEndDate": "string",
            "approvalDate": "string",
            "rejectionCode": "string",
            "rejectionDate": "string",
            "rejectionReason": "string",
            "cancellationCode": "string",
            "cancellationDate": "string",
            "jobContent": {
                "externalUrl": "string",
                "jobDescriptions": [
                    {
                        "languageIsoCode": "string",
                        "title": "string",
                        "description": "string"
                    }
                ],
                "company": {
                    "name": "string",
                    "street": "string",
                    "houseNumber": "string",
                    "postOfficeBoxNumber": "string",
                    "postOfficeBoxPostalCode": "string",
                    "postOfficeBoxCity": "string",
                    "postalCode": "string",
                    "city": "string",
                    "countryIsoCode": "string",
                    "website": "string",
                    "phone": "string",
                    "email": "string",
                    "surrogate": true
                },
                "employment": {
                    "startDate": "string",
                    "endDate": "string",
                    "shortEmployment": true,
                    "immediately": true,
                    "permanent": true,
                    "workloadPercentageMax": 0,
                    "workloadPercentageMin": 0,
                    "workForms": [
                        "string"
                    ]
                },
                "location": {
                    "remarks": "string",
                    "postalCode": "string",
                    "city": "string",
                    "communalCode": "string",
                    "regionCode": "string",
                    "cantonCode": "string",
                    "countryIsoCode": "string",
                    "coordinates": {
                        "latitude": 0,
                        "longitude": 0
                    }
                },
                "occupations": [
                    {
                        "avamOccupationCode": "string",
                        "workExperience": "string",
                        "educationCode": "string"
                    }
                ],
                "languageSkills": [
                    {
                        "languageIsoCode": "string",
                        "spokenLevel": "string",
                        "writtenLevel": "string"
                    }
                ],
                "applyChannel": {
                    "mailAddress": "string",
                    "emailAddress": "string",
                    "phoneNumber": "string",
                    "formUrl": "string",
                    "additionalInfo": "string"
                },
                "publicContact": {
                    "salutation": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "phone": "string",
                    "email": "string"
                }
            },
            "publication": {
                "startDate": "string",
                "endDate": "string",
                "euresDisplay": true,
                "euresAnonymous": true,
                "publicDisplay": true,
                "publicAnonymous": true,
                "restrictedDisplay": true,
                "restrictedAnonymous": true
            }
        }
    ],
    "currentElements": 0,
    "currentPage": 0,
    "first": true,
    "last": true,
    "totalElements": 0,
    "totalPages": 0
}
----

[cols="10,90"]
|===
| Name | Description

| content | The list of job advertisements
| currentElements | The number of job advertisements on this page
| currentPage | The current page number
| first | `true` if there are no previous pages
| last | `true` if there are no following pages
| totalElements | The total number of job advertisements on all pages
| totalPages | The total number of pages
|===

=== Response status
[cols="10,20,70"]
|===
| Code | Status | Description

| 200 | Ok | The page with job ads has been returned
| 401 | Unauthorized | User is not logged in
| 403 | Forbidden | User has not the required permission to perform this action
|===

