=== HTTP request
[source,http]
----
POST /0.2/joboffers HTTP/1.1
Accept: application/json;charset=UTF-8
Content-Type: application/json;charset=UTF-8
Authorization: Basic dXNlcjpwYXNzd29yZA==
Host: api.job-room.ch
Content-Length: 1629

{
  "publicationStartDate" : "2116-02-15",
  "publicationEndDate" : "2116-04-01",
  "reference" : "REF-847265",
  "url" : "https://www.missionrealty.ch/jobs/financial-manager/preview",
  "applicationUrl" : "https://www.missionrealty.ch/jobs/financial-manager/apply",
  "job" : {
    "title" : "Financial manager",
    "description" : "You will have to assist executives in making decisions that affect the organization",
    "workingTimePercentageFrom" : 60,
    "workingTimePercentageTo" : 90,
    "startDate" : "2116-03-01",
    "endDate" : "2118-05-31",
    "startsImmediately" : false,
    "permanent" : false,
    "location" : {
      "countryCode" : "CH",
      "locality" : "Lausanne",
      "postalCode" : "1017",
      "additionalDetails" : "Possibility of having interesting bonus"
    },
    "languageSkills" : [ {
      "language" : "2",
      "spokenLevel" : "very_good",
      "writtenLevel" : "very_good"
    }, {
      "language" : "5",
      "spokenLevel" : "very_good",
      "writtenLevel" : "good"
    } ]
  },
  "company" : {
    "name" : "Mission Realty",
    "countryCode" : "CH",
    "street" : "Glennerstrasse",
    "houseNumber" : "62",
    "locality" : "Genolier",
    "postalCode" : "1272",
    "phoneNumber" : "0225176355",
    "email" : "info@missionrealty.ch",
    "website" : "www.missionrealty.ch",
    "postbox" : {
      "number" : "1234",
      "locality" : "Genolier",
      "postalCode" : "1272"
    }
  },
  "contact" : {
    "title" : "mister",
    "firstName" : "Bertrand",
    "lastName" : "Boulé",
    "phoneNumber" : "0795721186",
    "email" : "bertrand.boule@missionrealty.ch"
  }
}
----

=== HTTP response
[source,http]
----
HTTP/1.1 201 Created
ETag: "0"
Location: https://api.job-room.ch/0.2/joboffers/93
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 1833

{
  "id" : 93,
  "publicationStartDate" : "2116-02-15",
  "publicationEndDate" : "2116-04-01",
  "reference" : "REF-847265",
  "url" : "https://www.missionrealty.ch/jobs/financial-manager/preview",
  "applicationUrl" : "https://www.missionrealty.ch/jobs/financial-manager/apply",
  "job" : {
    "title" : "Financial manager",
    "description" : "You will have to assist executives in making decisions that affect the organization",
    "workingTimePercentageFrom" : 60,
    "workingTimePercentageTo" : 90,
    "startDate" : "2116-03-01",
    "endDate" : "2118-05-31",
    "startsImmediately" : false,
    "permanent" : false,
    "location" : {
      "countryCode" : "CH",
      "locality" : "Lausanne",
      "postalCode" : "1017",
      "additionalDetails" : "Possibility of having interesting bonus"
    },
    "languageSkills" : [ {
      "language" : "2",
      "spokenLevel" : "very_good",
      "writtenLevel" : "very_good"
    }, {
      "language" : "5",
      "spokenLevel" : "very_good",
      "writtenLevel" : "good"
    } ]
  },
  "company" : {
    "name" : "Mission Realty",
    "countryCode" : "CH",
    "street" : "Glennerstrasse",
    "houseNumber" : "62",
    "locality" : "Genolier",
    "postalCode" : "1272",
    "phoneNumber" : "0225176355",
    "email" : "info@missionrealty.ch",
    "website" : "www.missionrealty.ch",
    "postbox" : {
      "number" : "1234",
      "locality" : "Genolier",
      "postalCode" : "1272"
    }
  },
  "contact" : {
    "title" : "mister",
    "firstName" : "Bertrand",
    "lastName" : "Boulé",
    "phoneNumber" : "0795721186",
    "email" : "bertrand.boule@missionrealty.ch"
  },
  "_links" : {
    "self" : {
      "href" : "https://api.job-room.ch/0.2/joboffers/93"
    },
    "jobOffer" : {
      "href" : "https://api.job-room.ch/0.2/joboffers/93"
    }
  }
}
----

=== Request fields
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| publicationStartDate | String | Date from which the job offer is visible on the publication medias. Job offer is published once that publicationStartDate is smaller than current date. | Not null.
Cannot be smaller than current date.
Cannot be modified once that job offer has been published.
| publicationEndDate | String | After this date, the job offer is removed from the publication medias. | Must be greater than publicationStartDate.
| reference | String | External reference (e.g. can be used to link API’s jobs to another id system). |
| url | String | Link to the original webpage of the job offer. |
| applicationUrl | String | Link to the webpage containing an application form. |
| job | Object | Description of the job.
(further information below) | Not null.
| company | Object | The company that offers the job.
(further information below) | Not null.
| contact | Object | Contact person about the job offer.
(further information below)
|===

==== job
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| job.title | String |  | Not null.
| job.description | String | Job description can contain basic HTML formatting. | Not null.
Length max 10000 characters.
| job.workingTimePercentageFrom | Number |  | Must be greater than 0.
workingTimePercentageFrom and workingTimePercentageTo have to be either both null or both defined.
| job.workingTimePercentageTo | Number |  | Must be greater or equal than workingTimePercentageFrom.
Must be less or equal than 100.
workingTimePercentageFrom and workingTimePercentageTo have to be either both null or both defined.
| job.startDate | String |  |
| job.endDate | String |  | Must be greater than startDate.
| job.startsImmediately | Boolean |  | Can’t be true if starteDate is defined.
| job.permanent | Boolean |  | Can’t be true if endDate is defined.
| job.location.countryCode | String |  | Not null.
Must be one of authorized country codes (see section <<Country codes>>).
| job.location.locality | String |  |
| job.location.postalCode | String |  | If not null, must be a valid swiss postal code if the job is located in Switzerland.
| job.location.additionalDetails | String | More information about job location can be added as free text. Note : this property is currently not shown on the publication medias. Work is in progress in order to integrate this feature. |
| job.languageSkills | Array | It is possible to define up to 5 language skills required by the job. | Size must be between 0 and 5.
| job.languageSkills[].language | String | Required language’s code. | Not null.
Must be one of authorized language codes (see section <<Language codes>>).
| job.languageSkills[].spokenLevel | String | Required spoken level. | Not null.
Must be in ('no_knowledge', 'basic_knowledge', 'good', 'very_good').
| job.languageSkills[].writtenLevel | String | Required written level. | Not null.
Must be in ('no_knowledge', 'basic_knowledge', 'good', 'very_good').
|===

==== company
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| company.name | String |  | Not null.
| company.countryCode | String |  | Not null.
Must be one of authorized country codes (see section <<Country codes>>).
| company.street | String |  |
| company.houseNumber | String |  |
| company.locality | String |  |
| company.postalCode | String |  | If not null, must be a valid swiss postal code if the company is located in Switzerland.
| company.phoneNumber | String |  |
| company.email | String |  |
| company.website | String |  |
| company.postbox.number | String |  |
| company.postbox.locality | String |  |
| company.postbox.postalCode | String |  | If not null, must be a valid swiss postal code if the company is located in Switzerland.
|===

==== contact
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| contact.title | String |  | Must be in ('mister', 'madam').
| contact.firstName | String  |  |
| contact.lastName | String |  |
| contact.phoneNumber | String |  |
| contact.email | String |  |
|===

=== curl request
[source,bash]
----
$ curl 'https://api.job-room.ch/0.2/joboffers' -i -u 'user:password' -X POST -H 'Accept: application/json;charset=UTF-8' -H 'Content-Type: application/json;charset=UTF-8' -d '{
  "publicationStartDate" : "2116-02-15",
  "publicationEndDate" : "2116-04-01",
  "reference" : "REF-847265",
  "url" : "https://www.missionrealty.ch/jobs/financial-manager/preview",
  "applicationUrl" : "https://www.missionrealty.ch/jobs/financial-manager/apply",
  "job" : {
    "title" : "Financial manager",
    "description" : "You will have to assist executives in making decisions that affect the organization",
    "workingTimePercentageFrom" : 60,
    "workingTimePercentageTo" : 90,
    "startDate" : "2116-03-01",
    "endDate" : "2118-05-31",
    "startsImmediately" : false,
    "permanent" : false,
    "location" : {
      "countryCode" : "CH",
      "locality" : "Lausanne",
      "postalCode" : "1017",
      "additionalDetails" : "Possibility of having interesting bonus"
    },
    "languageSkills" : [ {
      "language" : "2",
      "spokenLevel" : "very_good",
      "writtenLevel" : "very_good"
    }, {
      "language" : "5",
      "spokenLevel" : "very_good",
      "writtenLevel" : "good"
    } ]
  },
  "company" : {
    "name" : "Mission Realty",
    "countryCode" : "CH",
    "street" : "Glennerstrasse",
    "houseNumber" : "62",
    "locality" : "Genolier",
    "postalCode" : "1272",
    "phoneNumber" : "0225176355",
    "email" : "info@missionrealty.ch",
    "website" : "www.missionrealty.ch",
    "postbox" : {
      "number" : "1234",
      "locality" : "Genolier",
      "postalCode" : "1272"
    }
  },
  "contact" : {
    "title" : "mister",
    "firstName" : "Bertrand",
    "lastName" : "Boulé",
    "phoneNumber" : "0795721186",
    "email" : "bertrand.boule@missionrealty.ch"
  }
}'
----
