package ch.admin.seco.jobs.services.jobadservice.application.jobadvertisement.dto.create.legacy;

public enum LegacyDegreeEnum {
    PRIMAR_OBLIGATORISCHE_SCHULE,
    SEK_I_OBLIGATORISCHE_SCHULE,
    SEK_II_WEITERFUEHRENDE_SCHULE,
    SEK_II_GRUNDBILDUNG_EBA,
    SEK_II_GRUNDBILDUNG_EFZ,
    SEK_II_FACHMITTELSCHULE,
    SEK_II_BERUFSMATURITAET,
    SEK_II_FACHMATURITAET,
    SEK_II_GYMNASIALE_MATURITAET,
    TER_BERUFSBILDUNG_FA,
    TER_BERUFSBILDUNG_DIPL,
    TER_BACHELOR_FACHHOCHSCHULE,
    TER_BACHELOR_UNIVERSITAET,
    TER_MASTER_FACHHOCHSCHULE,
    TER_MASTER_UNIVERSITAET,
    TER_DOKTORAT_UNIVERSITAET,
    NOT_KNOWN
}
